### ISSUE TITLE
HTML escaping issues (PHPCS)

### ISSUE THREAD

**Issue by erfanimani** [JaJuMa-GmbH/hyva-faq-widget#1]
Hi there,

PHPCS (Magento 2 rules) complains about unescaped variables in the template.

I suggest to

1) escape output where necessary using the appropriate escape functions, and
2) add `/* @noEscape */` tags where unescaped output is desired

**Comment by JaJuMa** [comment]
Thanks @erfanimani - Fixed with release [1.1.2](https://github.com/JaJuMa-GmbH/hyva-faq-widget/releases/tag/1.1.2)
